events {}

http {
    resolver 127.0.0.11 valid=30s;

    server {
        listen 80;

        location /auth {
            set $upstream http://auth-service:8081;
            proxy_pass $upstream;
            proxy_set_header Host $host;
        }

        location /players {
            set $upstream http://player-service:8082;
            proxy_pass $upstream;
            proxy_set_header Host $host;
        }

        location /monsters {
            set $upstream http://monster-service:8083;
            proxy_pass $upstream;
            proxy_set_header Host $host;
        }

        location /invocations {
            set $upstream http://invocation-service:8084;
            proxy_pass $upstream;
            proxy_set_header Host $host;
        }

        location /fight {
            set $upstream http://fight-service:8085;
            proxy_pass $upstream;
            proxy_set_header Host $host;
        }

        location /leaderboard {
            set $upstream http://fight-service:8085;
            proxy_pass $upstream;
            proxy_set_header Host $host;
        }

        location /stamina {
            set $upstream http://stamina-service:8086;
            proxy_pass $upstream;
            proxy_set_header Host $host;
        }

        location / {
            set $upstream http://nintcha-front:3000;
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
